# Generated by Django 4.0.5 on 2022-06-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_neighbourhood_accounts_join_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_hood',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to='neighbourhood.neighbourhood'),
        ),
    ]
