# Generated by Django 4.0.5 on 2022-06-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_rename_accounts_neighbourhood_occupants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='admin',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Join_hood',
        ),
    ]
